trishan9/HelloWorld

- R/HelloWorld.R
- Ruby/HelloWorld.ru
Added Hello World in Ruby and R Programming language.
> Hello World in Ruby is added

- Python/leetcode-groupAnagrams.py
THIS FILE CONTAINS SOLUTION OF GROUP ANAGRAMS.
> Group Anagrams

- Python/non_repeated_char.py
- Python/palindrom.py
- Python/permutation.py
Added below python program in Python folder
1.First Non Repeated Character in string
2. Permutation
3. Palindrom
> 3 python program add by mahak under hacktoberfest2023 assigned issue

- Python/bubbleSort.py
- QBasic/hello.bas
This PR contains hello world program written in QBasic programming language and a bubble sorting algorithm written in python
> Added hello world in qbasic and bubble sort in python

- Java/BubbleSort.java
- Java/SelectionSort.java
Adding Bubble Sort and Selection Sort in Java
Issue #27
> Adding BubbleSort and Selection Sort in java

- Bhailang/helloworld.bhai
> Added bhail lang hello world

- Html/index.html
- Html/styles.css
Fixes: #30 #17
Hello world in html with cool animation from Kevin Powel
https://github.com/trishan9/HelloWorld/assets/85205148/2d487414-6b34-4c62-91fe-6411d9cfc93b
> Hello world in Html

- SQL/HelloWorld.sql
fixes #29 #17
Created a database for hello world a table(message,language)
Further contribution can be added in different languages using insert query
> Added Hello world for SQL

- MOJO/hello.mojo
Added a Hello World program for mojo language.  PR#40 
Please review and consider merging this pull request. Additionally, I kindly request the addition of the Hacktoberfest and Hacktoberfest-Accepted labels to this pull request.
Thank you!
@akashchaudhary-git
> Hello, world with a mojo source file

- Java/MergeSort.java
please review my code and merge it
thank you!!
> Added MergeSort.java

- F#/FSharpHelloWorld/FSharpHelloWorld.fsproj
- F#/FSharpHelloWorld/Program.fs
Hey @trishan9,
I've added the Hello World program for F# language.
Please review and consider merging this pull request. Additionally, I kindly request the addition of the hacktoberfest and hacktoberfest-accepted labels to this pull request.
Thank you!
> Added F# Console Hello World Application

- Go/Factorial.go
- Java/ReverseNo.java
solved issue #27
please mark it is hacktober fest accepted
> ReverseNo.Java

- QBasic/hello.bas
- helloWorld.chef
print hello world in chef language
> added a chef file

- Groovy/HelloWorld.groovy
Apache Groovy is a Java-syntax-compatible object-oriented programming language for the Java platform. It is both a static and dynamic language. 
To become the master of java one should lear this language
> Added Groovy Hello World program #28

- HelloWorld.m
- MATLAB/HelloWorld.m
> add Hello-World in MATLAB

- Java/DoubleLinkedList.java
- Java/LinkedList.java
As you permitted , I added the Java Codes. Fixes #27
> adding linkedlists

- Java/Search2DMatrixII.java
Added a Java program to search in 2D array using binary search.
> Implemented search in 2D array #27

- HelloWorld.j
Added the script for Hello World in 'J' Programming Language
> Added_J_Language

- HelloWorld.mal
- Java/VigenereCipher.java
Added the Vigener Cipher algorithm in java
> Vigener Cipher

- Hellowold.hs
print Hello world in Haskell Programming language #131 
added Helloworld.hs file
> Helloworld in haskell programming language #131

- Java/CyclicSort.java
- Java/InsertionSort.java
- Java/LinearSearchin2DArrays
- Java/ReverseAnArray.java
Heyy @trishan9 , I have made the necessary changes and Added some Java programs. Please merge my Pull request under hacktoberfest. Thanks!
> Added 4 java programs - Insertion Sort, ReverseAnArray, LinearSearchin2DArrays & CyclicSort

- C++/mergesort.cpp
Added implementation of mergesort in C++
> Added mergesort.cpp in C++ folder

- HelloWorld.jsx
This is for hacktoberfest, please put the [hacktoberfest-accepted] label before merge. Thank you!
> Add HelloWorld using jsx

- JavaProjects/LibraryManagementSystem.java
Description: A system that allows users to manage books in a library. Features include adding books, updating book information, borrowing and returning books, and tracking available books. Key Features:
User and Admin login
Add, delete, update, and search for books
Borrow and return books with due dates
> JavaProject : Library Management System

- JavaProjects/LibraryManagementSystem.java
- JavaProjects/StudentManagement.java
Description: A console-based application for managing student details like name, age, grade, and subjects. Key Features:
Add, delete, and update student information
Search for students by name
Display all student details
> JavaProject : Student Management System

- JavaProjects/LibraryManagementSystem.java
- JavaProjects/OnlineQuizSystem.java
- JavaProjects/StudentManagement.java
Description: A console-based quiz application where users answer questions and get their score at the end. Key Features:
Multiple-choice questions
Score calculation at the end
Feedback on the correct/incorrect answers
> JavaProject : Online Quiz System

- JavaProjects/LibraryManagementSystem.java
- JavaProjects/OnlineQuizSystem.java
- JavaProjects/StudentManagement.java
- JavaProjects/ToDoListApplication.java
Description: A simple task management tool to add, delete, and view tasks in a to-do list. Key Features:
Add tasks
Mark tasks as completed
View all tasks (completed and pending)
> JavaProject : To-Do List Application

- HelloWorld.vala
> Hello World in Vala

- SimpleHTMLCalc.html
Completed the hacktoberfest task, added a new simple html calculator as a project
> Added SimpleCalculator

- C++/Insertion Sort.cpp
I have added code for insertion sort. Kindly merge my code.
> Insertion Sort.cpp

- Simple HTML Programs #141.html
I have made the simple html program #141
> Create Simple HTML Programs #141.html

- Simple Python Programs #145.py
adding two matrics in Simple Python Programs #145
> Create Simple Python Programs #145.py

- MERGE SORT using cpp/Merge sort C++ #178.cpp
C++ program for the implementation of merge sort
> Created Merge sort C++ #178.cpp

- Simple Java Programs #144.java
> Create Simple Java Programs #144.java

- To_Do_List.rs
- helloworld
Adding To Do List Program in Rust.
> fix-issue-146

- C++/Pivot element in sorted rotated array.cpp
I have added code for finding pivot element in sorted rotated array. Please merge my code.
> Finding Pivot element in sorted rotated array.cpp

- SimpleGoPrograms/armstrong.go
- SimpleGoPrograms/binarysearch.go
- SimpleGoPrograms/fizzbuzz.go
Fixes#143
Added Simple go programs.
> Added simple go programs

- Rust/quick_sort.rs
A simple rust program for hacktoberfest.
> Added quick sort in rust

- Java/Sudoko.java
- JavaScript/CatchTheBallGame.html
Please add these codes under hacktoberfest-2024
> Added Sudoko game using java and Ball game 

- Python/emoji_translator.py
Summary:
This pull request adds a new Python project, Emoji Translator, which converts specific words into emojis. It’s a beginner-friendly tool designed to enhance programming skills and contribute to Hacktoberfest.
Features:
Input Translation: Users input a sentence, and the program translates specific words into emojis using a predefined dictionary.
Customizable Dictionary: Easy to expand with new words and emojis.
Run the program, input a sentence, and get the translated output with emojis.
Example:
Input: "I love pizza."
Output: "I ❤️ 🍕."
Thank you for reviewing my contribution!
> added emoji translator in python

- C++/bestTimeToBuyAndSellStock.cpp
hello @trishan9  sir,
i have succesfully added the solution of  "Best time to buy and sell stock-III"  problem without  any merge conflicts.
kindly add this PR under Hacktoberfest2024.
> added solution of <Best time to buy and sell stock-III>#213

- C++/Aggressive Cows Problem.cpp
Please accept the PR Under Hacktoberfest2024
> Aggressive Cows Problem

- Convays's life game.py
Please add this under Hactoberfest2024
> Create Convays's life game.py

- heapsort.cpp
Added "Heap Sort Algorithm" as "heapsort.cpp"
> Created heapsort.cpp

- C++/HangManGame.cpp
Kindly merge the pull request under Hacktoberfest2024, Thanku
> Add Hang Man Game in CPP

- Bat Ball Stump Game/cricket.css
- Bat Ball Stump Game/cricket.html
Hello @trishan9, I have added the Bat Ball Stump Game.
issue- #164.
Please review it and merge it under Hactoberfest-2024 label.
Thank You.
> Added Bat Ball Stump Game #164

- hello-world.clj
Kindly merge this PR under Hacktoberfest 2024, Thanku
> Add hello world in Clojure Language

- Linearsearch.c
It shows the complete description of how to create a linear search in c language , with comments to explain every step. It's beginner friendly and anyone can understand the algorithm.
> Created the file that shows linear search in c language.

- Binary_search.c
I have added the file Binary_search.c .  It contains complete implementation of the binary search algorithm in c language. I have added comments for almost every step which makes it beginner friendly and it could be understood by anyone. I have also explained and defined the binary search algorithm in comments at the top of the program. It is helpful for everyone including students and those preparing for placements. It is helpful for both theory as i have added all the necessary theory for the binary search algorithm and implementation as it can easily be implemented by anyone.
> Added Binary_search.c file.

- Hello word.hs
Added a hello word program in Haskell Programming language.
> Create Hello word.hs
